### ISSUE TITLE
Alterar script para suportar novo dump público

### ISSUE THREAD

**Issue by turicas** [turicas/socios-brasil#12]
A Receita Federal está disponibilizando um novo dump (http://idg.receita.fazenda.gov.br/orientacao/tributaria/cadastros/cadastro-nacional-de-pessoas-juridicas-cnpj/dados-publicos-cnpj) e ele parece ser igual ao que recebemos via LAI. Se for, o script pode ser aproveitado.

[Lista de CNAEs](https://concla.ibge.gov.br/classificacoes/download-concla.html).

Tarefas:

- [x] Baixar arquivo
- [x] Rodar script no arquivo baixado e verificar resultado
- [x] Verificar o PDF do layout e comparar com o recebido pela LAI (https://drive.google.com/drive/folders/1GqzpvfTYHaDXoVLCITKSeoLA7tSfr75W)
- [x] Verificar resultado
- [x] Alterar script para também baixar arquivo

**Comment by jhonata-menezes** [comment]
@turicas quero colaborar com o projeto, tenho uma base no momento com 30.718.385 de empresas (https://casadosdados.com.br/). No momento a quantidade vai crescer lentamente, mas acho que pode ajudar a todos. Os dados estão no MongoDB, segue exemplo do json.

```json
{
	"cnpj": "00360305000104",
	"cnpj_raiz": "00360305",
	"filial_numero": 1,
	"razao_social": "CAIXA ECONOMICA FEDERAL",
	"matrizfilial": "MATRIZ",
	"codigo_natureza_juridica": "2011",
	"descricao_natureza_juridica": "EMPRESA PUBLICA",
	"nome_fantasia": "CEF MATRIZ",
	"situacao_cadastral": "ATIVA",
	"data_situacao": ISODate("2005-11-03T00:00:00Z"),
	"logradouro": "SBS QUADRA 4 BLOCO A LOTE",
	"numero": "3/4",
	"complemento": "PRESI/GECOL 21 ANDAR",
	"cep": "70092900",
	"bairro": "ASA SUL",
	"municipio": "BRASILIA",
	"uf": "DF",
	"latitude": 0,
	"longitude": 0,
	"data_abertura": ISODate("1971-02-03T00:00:00Z"),
	"endereco": "",
	"telefones": [
		"61-4149290"
	],
	"motivo_situacao": "",
	"ente_federativo": "BR",
	"email": "gecol@caixa.gov.br",
	"capital_social": 5083531813.9,
	"situacao_especial": "",
	"data_situacao_especial": ISODate("0001-01-01T00:00:00Z"),
	"quadro_societario": [{
			"nome": "FABIO LENZA",
			"qualificacao": "Administrador"
		},
		{
			"nome": "ARNO MEYER",
			"qualificacao": "Administrador"
		},
		{
			"nome": "MARCELO CAMPOS PRATA",
			"qualificacao": "Administrador"
		},
		{
			"nome": "MARCOS FERNANDO FONTOURA DOS SANTOS JACINTO",
			"qualificacao": "Administrador"
		},
		{
			"nome": "NELSON ANTONIO DE SOUZA",
			"qualificacao": "Presidente"
		},
		{
			"nome": "PAULO HENRIQUE ANGELO SOUZA",
			"qualificacao": "Administrador"
		},
		{
			"nome": "JOSE ANTONIO EIRADO NETO",
			"qualificacao": "Administrador"
		},
		{
			"nome": "FLAVIO EDUARDO ARAKAKI",
			"qualificacao": "Administrador"
		}
	],
	"mensagem_quadro_societario": "",
	"atividade_principal": {
		"codigo": "6423-9/00",
		"descricao": "Caixas econômicas"
	},
	"atividade_secundaria": [],
	"codigo_ibge": 5300108,
	"codigo_gia": 0,
	"data_consulta": ISODate("2018-11-17T23:24:41Z"),
	"exception": "",
	"retorno_mensagem": "",
	"bloqueado": false
}
```

**Comment by augusto-herrmann** [comment]
Baixei os dados do link do site da Receita, mas parece que estão corrompidos.

```
$ file DADOS_ABERTOS_CNPJ.zip 
DADOS_ABERTOS_CNPJ.zip: Zip archive data, at least v4.5 to extract

$ unzip DADOS_ABERTOS_CNPJ.zip 
Archive:  DADOS_ABERTOS_CNPJ.zip
warning [DADOS_ABERTOS_CNPJ.zip]:  852063295 extra bytes at beginning or within zipfile
  (attempting to process anyway)
error [DADOS_ABERTOS_CNPJ.zip]:  start of central directory not found;
  zipfile corrupt.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
```

Qual é o tamanho e hash SHA-1 do arquivo que vocês receberam? O do site da Receita tem 5.147.030.696 bytes.

```
$ sha1sum DADOS_ABERTOS_CNPJ.zip 
cbc4ee46ebe45a9bfed3dc1fa0d45553b6a69455  DADOS_ABERTOS_CNPJ.zip
```

Alguém conseguiu processar esse arquivo?

**Comment by eriveltonguedes** [comment]
nós conseguimos, usamos o pdi. Tivemos de fazer um tratamento pois havia alguns caracteres estranhos. Na 2a vejo exatamente o que fizemos e informo melhor.

**Comment by mbello** [comment]
Realmente, o DADOS_ABERTOS.zip está corrompido. Baixei 2 vezes para ter certeza. sha1sum bate com o do Augusto.

sha1sum DADOS_ABERTOS_CNPJ.zip 
cbc4ee46ebe45a9bfed3dc1fa0d45553b6a69455  DADOS_ABERTOS_CNPJ.zip

Brincadeira, né? Parece que fazem o possível para liberar sem liberar.

**Comment by mbello** [comment]
Ok, descobri como abrir o arquivo. Ele parece corrompido, mas o zip (e não o unzip) têm uma funcionalidade para recuperar o que conseguir de um arquivo. Funcionou aqui:

```
zip -FF DADOS_ABERTOS_CNPJ.zip --out dados_abertos_cnpj.zip
Fix archive (-FF) - salvage what can
 Found end record (EOCDR) - says expect single disk archive
Scanning for entries...
 copying: F.K032001K.D81106D  (5147030446 bytes)
Central Directory found...
Zip64 EOCDR found ( 1 5147030598)...
Zip64 EOCDL found ( 1 5147030654)...
EOCDR found ( 1 5147030674)...
```
**Será que foram perdidos dados?**

```
unzip -Z dados_abertos_cnpj.zip
Archive:  dados_abertos_cnpj.zip
Zip file size: 5147030696 bytes, number of entries: 1
-rw-a--     4.5 fat 87007869830 tx d64N 18-Nov-22 19:06 F.K032001K.D81106D
1 file, 87007869830 bytes uncompressed, 5147030446 bytes compressed:  94.1%
```
Acho que não! São na verdade 87GB de dados (caramba!), comprimidos a uma boa taxa de 94,1% resultaram em um arquivo de 5,1GB comprimido que é praticamente o tamanho do download. Então acho que não houve perda de dados.

**Comment by mbello** [comment]
@turicas, fiz a conferência da especificação do Layout que vc tem no GDrive e da "nova" que está no site e são idênticos.

**Comment by mbello** [comment]
Pessoal, tentei ler do arquivo zip usando python e não consegui. O zip gerado pela RFB utiliza um formato proprietário que o python não suporta (NotImplementedError: compression type 9 (deflate64)). 

Para "rezipar" o arquivo eu usei o seguinte comando:

```
unzip -p DADOS_ABERTOS_CNPJ.zip | zip dados_abertos_cnpj.zip -
```

**Comment by mbello** [comment]
A propósito, não vou utilizar o código daqui pq não posso usar GPL3, quando terminar vou publicar meu código com outra licença, provavelmente CC0, e aviso aqui o local da publicação.

**Comment by turicas** [comment]
@mbello se fosse LGPL3 facilitaria pra ti?

**Comment by mbello** [comment]
@turicas Até facilitaria, mas agora já terminei minha implementação. Logo disponibilizo.

**Comment by davidschettini90** [comment]
Alguém que conseguiu abrir o arquivo poderia detalhar o passo pra gente?

**Comment by mbello** [comment]
Viu meus comentários acima? É só corrigir o arquivo:

zip -FF DADOS_ABERTOS_CNPJ.zip --out dados_abertos_cnpj.zip

Isso é no Linux, não tenho Windows nem Mac e não tenho a mínima idéia de como fazer isso nesses SOs.

**Comment by MorandiniMaicon** [comment]
https://github.com/fabioserpa/CNPJ-full

**Comment by turicas** [comment]
@davidschettini90 e @augusto-herrmann eu não tive problemas para abrir o arquivo, mas fiz em Python mesmo. Segue um exemplo de código para listar todos arquivos dentro do ZIP e imprimir as primeiras 10 linhas:

```python
import zipfile

filename = "DADOS_ABERTOS_CNPJ.zip"
zf = zipfile.ZipFile(filename)
for file_info in zf.filelist:
    internal_filename = file_info.filename
    print(internal_filename)
    fobj = zf.open(internal_filename)
    for index, line in enumerate(fobj, start=1):
        print(f"  [{index:02d}] {line.decode('iso-8859-15')}")
        if index == 10:
            break
```

**Comment by turicas** [comment]
@MorandiniMaicon vou ver o script que você recomendou, talvez tenham alguns fatores lá que passaram despercebidos na minha implementação. Você chegou a verificar os dados gerados pelo script?

**Comment by turicas** [comment]
Nota: na minha visão a melhor estratégia para trabalhar com dados desse tamanho é sempre descompactá-los e compactá-los em tempo de execução, exatamente como faço no script. Dessa forma, precisamos de menos espaço em disco para rodar o script e o overhead de processamento não é significativo. Por isso o script por padrão gera CSV (para já gerar compactado), daí depois é só importar em qualquer sistema de banco de dados (se vocês tem a [CLI da rows](http://turicas.info/rows/cli/) instalada dá pra converter CSVs compactados de maneira lazy para SQLite com: `rows csv2sqlite arquivo.csv.gz arquivo.sqlite`).

**Comment by fabioserpa** [comment]
> https://github.com/fabioserpa/CNPJ-full

Você chegou a tentar executar esse script usando como entrada o arquivo zipado? Estou sem o arquivo aqui nesse momento (estou baixando a nova versão disponibilizada pela RFB ontem, 03/04, mas está muito lento), porém como fiz o script usando "por baixo dos panos" uma função do pandas que aceita arquivos zipados, pode ser até que funcione, se ele não "pirar" com o tamanho do arquivo. Não me preocupei tanto com isso uma vez que é um único arquivo a ser atualizado na melhor das hipóteses trimestralmente, mas, sim, pode ser interessante disponibilizar uma versão que leia zipado, se já não funcionar. 
Me preocupei mais, em um primeiro momento, em aproveitar os recursos do pandas/numpy de operações vetorizadas para maximizar o desempenho, conseguindo com que no meu notebook normal conclua o processo em aprox. 1 hora e 40 para gerar CSVs, ou umas 2 horas para gerar diretamente uma base SQLite.

**Comment by turicas** [comment]
@fabioserpa, sinceramente eu não acho que "limitação de espaço em disco" seja um problema. A minha questão é justamente diminuir o tempo de extração total pois facilita atualizações em bases de dados e também ajustes no script (o arquivo costuma vir corrompido - se toda vez que eu alterar o script tiver que rodar um script que demora muitas horas, o trabalho inteiro vai ser bem lento). Descompactar antes, além de consumir mais espaço, necessariamente demora mais tempo. O tempo de 1h40min que você comentou é o tempo total de descompactar o arquivo, fazer a extração e escrever os CSVs?

**Comment by turicas** [comment]
Atualização: baixei a base nova (disponibilizada em maio) e parece que, mais uma vez, o arquivo está corrompido. :( Dessa vez, `zip -F` e `zip -FF` não resolveram muito: o arquivo ZIP pode ser lido pelo Python, mas no final dá CRC error.
Estou fazendo algumas alterações no parser para corrigir alguns problemas que existiam antes e otimizar algumas etapas, mas o resultado não ficará muito bom caso o arquivo de origem continue corrompido (apesar de conseguir ler o conteúdo, em torno de 183k linhas possuem tamanhos muito diferentes do esperado, produzindo resultados incorretos para muitos registros).

**Comment by fabioserpa** [comment]
É, depois de baixar duas vezes (com downloads que levaram dias) e nas duas vezes dar CRC na descompactação e ambos produzirem o mesmo resultado na tentativa de carga (mesmas divergências), fiquei convencido de que há um problema no arquivo lá na origem.
Não sei se reparou, mas a versão de março/abril continha aprox. 18,5 milhões de registros de sócios. A versão atual, de maio, segundo a informação no trailler, contém quase 26 milhões de registros de sócios, ou seja, um aumento de 40% em dois meses. Faz sentido isso? Ou será que começaram a colocar/replicar informação de sócio para as filiais?

**Comment by turicas** [comment]
@fabioserpa eu baixei em paralelo o arquivo nos servidores do Brasil.IO e disponibilizei no mirror (que é bem mais rápido): https://data.brasil.io/mirror/socios-brasil/DADOS_ABERTOS_CNPJ.zip (SHA1SUM do arquivo em https://data.brasil.io/mirror/socios-brasil/SHA1SUMS). Sobre o problema de estar corrompido: estou fazendo testes em mais detalhes para usar o diagnóstico em um pedido de acesso à informação.
Sobre o aumento do número de sócios, não sei o que pode ser. Depois que terminar os testes vou começar a investigar os novos dados.

**Comment by fabioserpa** [comment]
@turicas, acabei de fazer uma verificação rápida na base convertida, mesmo que prejudicada pelo arquivo corrompido, e tudo indica que é a aquela hipótese mesmo, de agora incluir registro de sócios para as filiais, e não somente para a matriz, como era antes. Só que, pelo menos com base nas primeiras filiais do BB que olhei, os registros de sócios são idênticos para todas as filiais, então, não parece ser uma informação realmente nova. E essa é a explicação para o arquivo ter aumentado tanto em tão pouco tempo.

**Comment by turicas** [comment]
Fiz um pedido de acesso à informação perguntando sobre essa questão dos sócios e pedindo para consertarem o arquivo corrompido.

**Comment by lraitz** [comment]
Olá, você teve algum posicionamento sobre o chamado? e esse arquivo disponibilizado é o de 15 de maio/2019?

**Comment by fabioserpa** [comment]
A RF disponibilizou a base, agora dividindo em 20 arquivos zip. Aparentemente não há arquivo problemático dessa vez. Pelo que vi, mantiveram o esquema de relacionar os sócios tanto para a matriz quanto para as filiais.

**Comment by turicas** [comment]
@lraitz não me responderam ainda, mas como o @fabioserpa disse, eles agora mudaram a forma de disponibilizar os arquivos (e está mais lento que antes). Estou baixando nos servidores do Brasil.IO e subindo num mirror, pra quem quiser baixar mais rapidamente, atualizações nessa thread: https://twitter.com/turicas/status/1138151318558793729 (em breve jogarei no mirror do Brasil.IO, pra facilitar os downloads, dado que não é tão simples baixar via linha de comando do Google Drive pois ele não gera uma URL fácil).

**Comment by turicas** [comment]
Corrigido em b675675cf7f13434decffda9e56995fc1571bc87.

**Comment by lraitz** [comment]
Também não me responderam meu chamado, mas agora ao menos melhorou, melhor assim do que com aquele arquivo grande. Sempre usei com Oracle e estou gostando desta forma no sqlite. muito bom trabalho.
