### ISSUE TITLE
OverflowError

### ISSUE THREAD

**Issue by milcent** [turicas/socios-brasil#13]
Após instalar as dependências, ao tentar descompactar como indicado, obtenho o erro abaixo:
`Traceback (most recent call last):
  File "extract_dump.py", line 27, in <module>
    import rows
  File "C:\Users\milcent\AppData\Local\Continuum\Anaconda3\lib\site-packages\row
s\__init__.py", line 22, in <module>
    import rows.plugins as plugins
  File "C:\Users\milcent\AppData\Local\Continuum\Anaconda3\lib\site-packages\row
s\plugins\__init__.py", line 20, in <module>
    from . import plugin_csv as csv  # NOQA
  File "C:\Users\milcent\AppData\Local\Continuum\Anaconda3\lib\site-packages\row
s\plugins\plugin_csv.py", line 34, in <module>
    unicodecsv.field_size_limit(sys.maxsize)
OverflowError: Python int too large to convert to C long`
Alguma dica de como resolver?
Grato,
Marcel Milcent

**Comment by turicas** [comment]
Essa issue tem a ver com uma mudança recente na biblioteca rows, que foi lançada na versão 0.4.0. Você poderia [criar a issue no repositório da rows](https://github.com/turicas/rows/issues/new), por favor? Daí discutimos por lá. Adicione também informações do seu ambiente (sistema operacional, 32/64bits, versão do Python etc.)

**Comment by milcent** [comment]
Claro, sem problema!
