### ISSUE TITLE
Especificação incorreta do arquivo de CNAEs secundários

### ISSUE THREAD

**Issue by arloc** [turicas/socios-brasil#15]
O formato correto das entradas de CNAEs seria trazer uma relação muitos para um com as empresas, porém ele sempre está em um para um.

Na especificação não consta o conteúdo da coluna que possui os caracteres entre: 25-710.
Porém na realidade ele retorna os demais CNAEs secundários da empresa.

Por exemplo a Petrobras:
> CÓDIGO E DESCRIÇÃO DAS ATIVIDADES ECONÔMICAS SECUNDÁRIAS
> - 06.00-0-01 - Extração de petróleo e gás natural
> - 35.20-4-01 - Produção de gás; processamento de gás natural
> - 46.81-8-01 - Comércio atacadista de álcool carburante, biodiesel, gasolina e demais derivados de petróleo, exceto lubrificantes, não realizado por transportador retalhista (T.R.R.)

No arquivo de CNAEs encontramos:
`F,,33000167000101,600001,35204014681801000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000`

Para corrigir este "problema" precisaremos alterar o funcionamento da função `parse_row` e de sua chamada para que uma linha do arquivo da Receita Federal gere diversas linhas em nosso arquivo de CNAEs.

**Comment by turicas** [comment]
Corrigido em b675675cf7f13434decffda9e56995fc1571bc87.
