### ISSUE TITLE
Possível processar dados empresas e sócios em um único csv?

### ISSUE THREAD

**Issue by RafaelPavanati** [turicas/socios-brasil#19]
Gostaria de saber se alguém já tentou gerar apenas um arquivos com a lista de sócios em cada CNPJ

**Comment by turicas** [comment]
@RafaelPavanati, o código não foi feito pensado nisso, mas talvez dê para fazer uma simples adaptação para gerar apenas um dos CSVs de saída - porém o script precisará percorrer a mesma quantidade de dados, dado que todos os tipos de registros estão misturados no mesmo arquivo, então acredito que não ficará **muito** mais rápido o processamento. A função que precisaria ser alterada é essa: https://github.com/turicas/socios-brasil/blob/master/extract_dump.py#L142
Você teria disponibilidade para fazer essa alteração? Acho que poderíamos passar como parâmetro na linha de comando quais CSVs queremos exportar, sendo o padrão "all".
