### ISSUE TITLE
Empresas sem dados de sócios

### ISSUE THREAD

**Issue by rdahis** [turicas/socios-brasil#33]
Parece haver 30027154 empresas sem dados de sócios. Sabe o que explica isso?

Fiz um merge entre a base de empresas e sócios (pessoas físicas) em cima do CNPJ das empresas.

Isso ainda não conta com o merge de empresas com sócios PJs. Mas o número de sócios PJ únicos é só 163982, então a diferença não pode vir daí.

**Comment by jlcd** [comment]
Qual foi seu racional pra chegar nesse número?
Até onde me recordo o número total de CNPJs é de aprox 18M.

**Comment by rodrigopmsilva** [comment]
Algumas Naturezas Jurídicas não permitem o preenchimento do quadro de sócios e administradores, logo não estarão na base de dados Públicos. Porém, não sei se essa situação abrange mais de ⅔ dos CNPJs, achei esse número alto.

**Comment by fabioserpa** [comment]
Mas é isso mesmo. Só de empresários individuais são aprox. 23 milhões.

**Comment by turicas** [comment]
@rdahis vou fechar essa issue, dado que esse não é um problema com o código e sim uma característica dos dados, ok?
Você pode checar o código da natureza jurídica da empresa para identificar qual não terá sócios (veja a issue #45 - estou trabalhando na melhora disso).
