### ISSUE TITLE
Erro na biblioteca rows

### ISSUE THREAD

**Issue by williamwaillant** [turicas/socios-brasil#34]
Alguém bateu com esse erro na hora de enviar para o banco?

"RuntimeError: Command not found: ['psql', '-c', 'CREATE TABLE IF NOT EXISTS "empresa""

**Comment by turicas** [comment]
@williamwaillant você precisa ter o comando `psql` (cliente do PostgreSQL) instalado em sua máquina para esse comando funcionar. Esse comando da rows só foi testado em sistemas GNU/Linux (Debian, pra ser mais específico).
