### ISSUE TITLE
Problemas no download: Não completou download e não há arquivos em data/output/

### ISSUE THREAD

**Issue by kvieirap** [turicas/socios-brasil#37]
Estou executando o download em um Linux Debian e usando o mirror da receita. O arquivo DADOS_ABERTOS_CNPJ_01.zip baixou entretanto o DADOS_ABERTOS_CNPJ_02.zip falhou. O arquivo DADOS_ABERTOS_CNPJ_01.zip está na pasta data/download e na pasta data/output não há nenhum arquivo.  

[#d857d1 0B/0B CN:1 DL:0B]
07/23 18:03:15 [ERROR] CUID#7 - Download aborted. URI=http://200.152.38.155/CNPJ/DADOS_ABERTOS_CNPJ_02.zip
Exception: [AbstractCommand.cc:340] errorCode=2 Tempo limite esgotado.

07/23 18:03:15 [NOTICE] Download GID#d857d17a4da0994a não concluído:

Resultados do Download:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
d857d1|ERR |       0B/s|http://200.152.38.155/CNPJ/DADOS_ABERTOS_CNPJ_02.zip

Legenda de estados:
(ERR):ocorreu um erro.

aria2 vai retomar o download se a transferência for reiniciada.
Caso tenha havido algum erro, veja o arquivo de log. Veja a opção '-l' na ajuda/página de manual para detalhes.

**Comment by placidodaniel** [comment]
Acredito que foi apenas alguma coisa com a sua internet. Tente denovo...

**Comment by kvieirap** [comment]
Consegui baixar pelo mirror do brasil.io
