### ISSUE TITLE
Erro de sintaxe no arquivo extract_dump.py

### ISSUE THREAD

**Issue by kvieirap** [turicas/socios-brasil#38]
Erro ao executar o extract_dump.py na linha 166. Erro de sintaxe.

ERRO DE SINTAXE
```
  File "extract_dump.py", line 166
    f"Opção pelo Simples inválida: {row['opcao_pelo_simples']} (CNPJ: {row['cnpj']})"

                                                                                       ^
SyntaxError: invalid syntax

```

**Comment by placidodaniel** [comment]
Você precisa executar o script com python versão superior a 3.6. Provavelmente você esta usando uma versão anterior do python.

**Comment by turicas** [comment]
O problema é a versão do Python. Como foi falado, precisa ser 3.6+.

Caso você não precise alterar as opções do script, sugiro baixar os dados já convertidos de https://data.brasil.io/dataset/socios-brasil/_meta/list.html

**Comment by kvieirap** [comment]
Consegui executar, editei o arquivo run.sh para forçar a execução em python3

**Comment by turicas** [comment]
@kvieirap o ideal seria você utilizar o [pyenv](https://github.com/pyenv/pyenv) para gerenciar as versões do Python na sua máquina e então criar um virtualenv para o projeto com a versão correta.

**Comment by kvieirap** [comment]
Vou pesquisar sobre, obrigado pela dica!
