### ISSUE TITLE
Erro na importação da tabela socio.csv para Postgresql

### ISSUE THREAD

**Issue by kvieirap** [turicas/socios-brasil#39]
Ao executar:

`rows pgimport --schema=schema-full/socio.csv data/output/socio.csv.gz $POSTGRESQL_URI socio`

Obtenho como erro:

```
  File "/usr/local/lib/python3.7/dist-packages/rows/utils.py", line 976, in pgimport
    raise ValueError('CSV field names are not a subset of schema field names')
ValueError: CSV field names are not a subset of schema field names
```

**Comment by turicas** [comment]
@kvieirap como você gerou o arquivo `data/output/socio.csv.gz`? Se foi sem alterações no `run.sh`, você deve usar o schema `schema/socio.csv`. O `schema-full` só funciona caso você tenha passado `--no_censorship` para o `extract_dump.py`.

**Comment by kvieirap** [comment]
Isso, gerei com base no `--no_censorship`.

Percebi que era um problema no schema então criei uma tabela a parte. O erro está no nome da coluna `nome_pais_socio`. Tive que alterar o nome da coluna para `nome_pais` e então o `pgimport` (sem schema rodou). Talvez se fizesse essa alteração no csv antes de rodar, não teria problema.

**Comment by turicas** [comment]
Opa, era um erro no arquivo `schema-full/socio.csv` então. Acabei de corrigir no commit bc98253. Obrigado!

**Comment by kvieirap** [comment]
Depois de alguns erros, percebi que se alterar no csv o nome da coluna `nome_pais_socio` para `nome_pais`, o pgimport roda.
