### ISSUE TITLE
Undefined name: partners

### ISSUE THREAD

**Issue by cclauss** [turicas/socios-brasil#4]
https://github.com/turicas/socios-brasil/blob/master/socios.py#L97-L100

flake8 testing of https://github.com/turicas/socios-brasil on Python 3.6.4

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./socios.py:97:36: F821 undefined name 'partners'
                    for partner in partners:
                                   ^
./socios.py:100:51: F821 undefined name 'partners'
                    yield {**company, 'partners': partners}
                                                  ^
2     F821 undefined name 'partners'
```

**Comment by turicas** [comment]
[This variable is defined inside the loop](https://github.com/turicas/socios-brasil/blob/master/socios.py#L132), so it's not a bug.
