### ISSUE TITLE
SyntaxError: invalid syntax no arquivo extract_dump.py

### ISSUE THREAD

**Issue by frankcaramelo** [turicas/socios-brasil#41]
**Pode me ajudar a corrigir o erro abaixo?** 

![Anotação 2020-08-10 195502](https://user-images.githubusercontent.com/22700008/89839143-6e6ab480-db43-11ea-9739-6b42892f64d5.png)

**Comment by turicas** [comment]
Qual versão do Python? Esse script requer 3.7+, como diz o README.

**Comment by frankcaramelo** [comment]
![Anotação 2020-08-12 180028](https://user-images.githubusercontent.com/22700008/90067590-b87ba380-dcc5-11ea-96b4-2b2613604621.png)

**Comment by turicas** [comment]
Você precisa instalar as dependências, [conforme a documentação](https://github.com/turicas/socios-brasil#rodando).
