### ISSUE TITLE
Falta o arquivo empresa-socia.csv.gz

### ISSUE THREAD

**Issue by VictorOF** [turicas/socios-brasil#43]
Quando tento executar o segundo comando do readme para importar os dados para um banco, recebo o seguinte erro:

`FileNotFoundError: [Errno 2] No such file or directory: 'data/output/empresa-socia.csv.gz'`

Executei o run com o --no_censorship e esse arquivo não foi gerado.

Estou usando Python 3.7.8 e ubuntu 16.04.

Edit:
falta o arquivo cnae-secundaria também:
`FileNotFoundError: [Errno 2] No such file or directory: 'schema/cnae-secundaria.csv'`

**Comment by turicas** [comment]
Esse é o antigo nome do atual `holding.csv.gz` - corrigi no README em 84878c6.
