### ISSUE TITLE
Siglas para UF

### ISSUE THREAD

**Issue by rodolfo-viana** [turicas/socios-brasil#5]
Conforme falamos sobre possíveis formas de reduzir o tamanho dos arquivos, posso mandar PR com a troca da unidade federativa para a sigla correspondente? Acha que seria útil?

**Comment by turicas** [comment]
Resolvi no commit a8a8c60 (e já joguei os dados atualizados em [2018-02-02](https://drive.google.com/drive/u/0/folders/1qbE71dbuDb0KI1LBNOoDxNwSGnJStYI-)). Não muda quase nada do tamanho compactado (porque a compactação dá conta da repetição do nome das UFs), mas muda bastante no tamanho descompactado:

- `socios-brasil.sqlite`: de 2407 MB para 2247MB;
- `Brasil.csv`: de 2228 MB para 2078 MB.
