### ISSUE TITLE
Erro de Syntax

### ISSUE THREAD

**Issue by benevides** [turicas/socios-brasil#51]
Ol'a, conseguem me dar uma ajuda, estou executando o processo, mas depois do download estou recebendo essa mensagem de erro.

Grato

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
3d456e|OK  |   6.2MiB/s|data/download/DADOS_ABERTOS_CNPJ_20.zip

Status Legend:
(OK):download completed.

real	0m44,591s
user	0m0,115s
sys	0m4,266s
  File "extract_dump.py", line 163
    raise ValueError(f"Opção pelo Simples inválida: {row['opcao_pelo_simples']} (CNPJ: {row['cnpj']})")
                                                                                                        ^
SyntaxError: invalid syntax

**Comment by turicas** [comment]
Você está usando uma versão antiga do Python. No README é mencionado que você precisa da 3.7 ou superior.
