### ISSUE TITLE
Consumir api socios-brasil pelo Insomnia

### ISSUE THREAD

**Issue by austre** [turicas/socios-brasil#52]
Pessoal,

Quando eu tento consumir a api "https://brasil.io/dataset/socios-brasil/empresas/" recebo esse retorno pelo Insomnia. Não estou conseguindo acertar o uso dessa api especificamente.
![image](https://user-images.githubusercontent.com/4764413/118202497-7c31cb00-b430-11eb-8941-939acc825aad.png)

![image](https://user-images.githubusercontent.com/4764413/118202575-9cfa2080-b430-11eb-8095-35fbc685a4d7.png)

![image](https://user-images.githubusercontent.com/4764413/118203238-03337300-b432-11eb-97f0-d2d30463164e.png)

**Comment by turicas** [comment]
Veja a documentação de acesso à API em nosso blog:

- [Como acessar os dados do Brasil.IO](https://blog.brasil.io/2020/10/10/como-acessar-os-dados-do-brasil-io/)
- [Nossa API será obrigatoriamente autenticada](https://blog.brasil.io/2020/10/31/nossa-api-sera-obrigatoriamente-autenticada/)

**Comment by austre** [comment]
@turicas eu fiquei ontem testando várias opções a noite, vi e li os dois links que você indicou algumas vezes. Só que não estou percebendo o que falta para funcionar.

[Nossa API será obrigatoriamente autenticada](https://blog.brasil.io/2020/10/31/nossa-api-sera-obrigatoriamente-autenticada/)
Eu já estou com minha chave api e utilizo ela no Insomnia através de variável de ambiente, a parte roxa indica o uso dessa variável de ambiente que criei. Estou apenas detalhando para que os leitores não familiarizados com o Insomnia entenda melhor.
![image](https://user-images.githubusercontent.com/4764413/118257851-7c0fea80-b485-11eb-99fe-546abb11a3f4.png)

Eu até postei [neste link](https://gist.github.com/turicas/3e3621d61415e3453cd03a1997f7473f#gistcomment-3742084) quando consegui resolver o consumo do dataset covid19 pelo Insomnia.

Hoje, junto com a escrita dessa resposta eu foi testando novamente a api do dataset covid19 que relatei ter tido sucesso [neste link](https://gist.github.com/turicas/3e3621d61415e3453cd03a1997f7473f#gistcomment-3742084), só que já não obtive sucesso. Vou colocar o print da tela completa para registrar a data e hora do teste.

Teste feito igual ao do link mencionado. Testei também colocar a chave api direto ao invés de utilizar a variável de ambiente do Insomnia, mas retorna a mesma mensagem.
![image](https://user-images.githubusercontent.com/4764413/118259276-584da400-b487-11eb-9fd1-92f97fe90a01.png)

Uma possibilidade que imagino é que a minha chave api foi bloqueada devido a quantidade de requisições, como fala nos links que você mencionou @turicas 

Mas, não tenho feito de forma automática e sim manual pelo Insomnia. Contudo, não encontrei como posso verificar se a minha chave api está bloqueada ou não.

Acho que é isso, já escrevi bastante. Peço que tenhas paciência na leitura, não estou com o objetivo de "apontar o dedo" ou algo negativo sobre o projeto, pois, eu conheci esse projeto **ontem a noite** e fiquei até 1h da manhã debruçado nele para conhecer mais. Só estou tentando encontrar uma forma de utilizar corretamente a api para depois usá-la de forma mais automática, segura e com parcimônia assim como você orientou.

Obrigado!
