### ISSUE TITLE
Erro de sintáxe na hora de exetuar o run.sh

### ISSUE THREAD

**Issue by ThallesBogar** [turicas/socios-brasil#55]
Estou tendo esse erro ao executar `./run.sh`.

File "extract_dump.py", line 163
    raise ValueError(f"Opção pelo Simples inválida: {row['opcao_pelo_simples']} (CNPJ: {row['cnpj']})")
                                                                                                        ^
SyntaxError: invalid syntax

real	0m0,011s
user	0m0,011s
sys	0m0,001s

Minha versão do python é a 3.7, conforme mostra o comando abaixo: 

`thalles@debian:~/cnpjBR/socios-brasil$ python -V 
Python 3.7.3
`

Não tenho conhecimento em python, vou utilizar os dados extraídos da biblioteca através de outra linguagem, portanto não sei dizer se código realmente está errado ou se é algum erro meu de instalação.

**Comment by ThallesBogar** [comment]
Me parece que o problema é a letra "f" antes do início das strings dentro de `ValueError`. Isso está acontecendo em várias linhas do arquivo `extract_dump.py`. Removi a letra "f" em todas as linhas e parou de acusar erro de sintáxe.

**Comment by turicas** [comment]
As f-strings foram adicionadas no Python 3.6, então se você realmente rodou com a 3.7 esse erro de sintaxe não deveria aparecer.
