### ISSUE TITLE
SP, nome de duas empresas em branco

### ISSUE THREAD

**Issue by sulram** [turicas/socios-brasil#6]
@turicas, tive que incluir o nome de duas empresas de SP para colocar o dataset no Neo4j.

Fiz uma busca no Sublime Text com o regex `[0-9]+,,` e encontrei esses 2 cnpjs sem nome da empresa:

- 08013165000533 (linhas 2904408–2904411)
- 08393057000533 (linhas 3088255–3088256)

abs!

**Comment by turicas** [comment]
Obrigado pelo report. Não tem muito o que fazer, dado que a informação vem errada da Receita Federal.
Coloquei esse detalhe no README (seção Erros) e entrei em contato com eles para ver se consertam.
